name: HolofansLobby
version: '1.0-SNAPSHOT'
main: me.f0reach.holofans.lobby.HolofansLobby
api-version: '1.21'
depend: [ ]
softdepend:
  - Vault
commands:
  lobby:
    description: Teleport to the lobby
    usage: /lobby
  othello:
    description: Minigame
    usage: /othello
  gomoku:
    description: Minigame
    usage: /gomoku
permissions:
  lobby.admin:
    description: Teleport to the lobby
    default: op